version: "3"
services:
  loggie-frontend:
    image: loggie-frontend:latest
    ports:
      - 5173:5173
  loggie-backend:
    image: loggie-backend:latest
    environment:
      - FRONTEND_PORT=5173
      - SERVER_PORT=8080
    ports:
      - 8080:8080
