/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    LogTable: typeof import('./src/components/LogTable.vue')['default']
    MainLayout: typeof import('./src/components/layouts/MainLayout.vue')['default']
    Navbar: typeof import('./src/components/layouts/Navbar.vue')['default']
    PageTitle: typeof import('./src/components/layouts/PageTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layouts/Sidebar.vue')['default']
  }
}
